### ISSUE TITLE
Suitable for applications such as LeoFS?

### ISSUE THREAD

**Issue by liuzhen** [dhtech/snmpexporter#2]
Quite new to snmp things, but is it suitable for LeoFS or the like?

https://leo-project.net/leofs/docs-old/configuration/configuration_4.html
LeoFS is an S3 compatible object storage system, from which I want to gather the data.

The whole thing is, I already have a working TSDB of dalmatinerdb, which by the design has a proxy to scape as prometheus, and I need to gather data from various services such as LeoFS as mentioned above.

I have tried the official  snmp_exporter, but it does not compile on SmartOS (like Solaris).

**Comment by Luppii** [comment]
Yes - I see no reason why it would not work for LeoFS. You will have to edit snmpexporter.yaml accordingly. Give it a try!

**Comment by liuzhen** [comment]
thank you.
